# Day_1

## Array

In [1]:
import numpy as np

In [2]:
x = [1,2,3,4]
y = np.array(x)

In [3]:
print(type(y))

<class 'numpy.ndarray'>


In [4]:
l = []
for i in range(1,5):
    int_1 = int(input('Enter the data'))
    l.append(int_1)
print(np.array(l))

ValueError: invalid literal for int() with base 10: ''

In [5]:
print(y.ndim)

1


In [6]:
d1 = np.array([1,2,3,4,5,6,7])
d2 = np.array([[1,2,3,4,5,6,7]])
d3 = np.array([[[1,2,3,4,5,6]]])

In [7]:
print(d2.ndim)
print(d3.ndim)

2
3


In [8]:
d2 = np.array([[1,2,3],[1,2,3]])
print(d2)
print(d2.ndim)

[[1 2 3]
 [1 2 3]]
2


In [9]:
d3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(d3)
print(d3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [10]:
dn = np.array([1,2,3,4],ndmin=10)
print(dn)
print(dn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Zeros

In [11]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4),float)
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones 

In [12]:
ar_one = np.ones(4)
ar_ones1 = np.ones((3,4))
print(ar_one)
print(ar_ones1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Empty Array

In [13]:
empty = np.empty(4) 
print(empty)

[1. 1. 1. 1.]


## Range

In [14]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [15]:
## Diagnol

In [16]:
ar_dia = np.eye(3)
ar_dia_2 = np.eye(5,3)
print(ar_dia)
print(ar_dia_2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Linespace

In [17]:
ar_lin = np.linspace(1,20,num= 20,)
print(ar_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


## Random

## Rand()

In [18]:
var = np.random.rand(4)
print(var)

[0.60629305 0.14768605 0.08442768 0.64969965]


In [19]:
var1 = np.random.rand(2,5,)
var1

array([[0.01748461, 0.39245053, 0.25444094, 0.71431959, 0.01824858],
       [0.84721302, 0.5755421 , 0.37076733, 0.56972314, 0.18459465]])

## randn()

In [20]:
var2 = np.random.randn()
print(var2)

0.11742120341711719


## randf()

In [21]:
var3 = np.random.ranf((3,4))
print(var3)

[[0.40615247 0.39890294 0.80426155 0.35378986]
 [0.36116235 0.50355871 0.55115391 0.34099645]
 [0.45370747 0.98293343 0.536285   0.21749118]]


## randint()

In [ ]:
var4 = np.random.randint(1,5,4)
print(var4)