# Day_1

## Array

In [1]:
import numpy as np

In [2]:
x = [1,2,3,4]
y = np.array(x)

In [3]:
print(type(y))

<class 'numpy.ndarray'>


In [4]:
l = []
for i in range(1,5):
    int_1 = int(input('Enter the data'))
    l.append(int_1)
print(np.array(l))

ValueError: invalid literal for int() with base 10: ''

In [ ]:
print(y.ndim)

1


In [ ]:
d1 = np.array([1,2,3,4,5,6,7])
d2 = np.array([[1,2,3,4,5,6,7]])
d3 = np.array([[[1,2,3,4,5,6]]])

In [ ]:
print(d2.ndim)
print(d3.ndim)

2
3


In [5]:
d2 = np.array([[1,2,3],[1,2,3]])
print(d2)
print(d2.ndim)

[[1 2 3]
 [1 2 3]]
2


In [6]:
d3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(d3)
print(d3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [7]:
dn = np.array([1,2,3,4],ndmin=10)
print(dn)
print(dn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Zeros

In [8]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4),float)
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones 

In [9]:
ar_one = np.ones(4)
ar_ones1 = np.ones((3,4))
print(ar_one)
print(ar_ones1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Empty Array

In [10]:
empty = np.empty(4) 
print(empty)

[1. 1. 1. 1.]


## Range

In [11]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [12]:
## Diagnol

In [13]:
ar_dia = np.eye(3)
ar_dia_2 = np.eye(5,3)
print(ar_dia)
print(ar_dia_2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Linespace

In [19]:
ar_lin = np.linspace(1,20,num= 20,)
print(ar_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


## Random