# Day_1

## Array

In [3]:
import numpy as np

In [4]:
x = [1,2,3,4]
y = np.array(x)

In [5]:
print(type(y))

<class 'numpy.ndarray'>


In [6]:
l = []
for i in range(1,5):
    int_1 = int(input('Enter the data'))
    l.append(int_1)
print(np.array(l))

[1 2 3 4]


In [7]:
print(y.ndim)

1


In [8]:
d1 = np.array([1,2,3,4,5,6,7])
d2 = np.array([[1,2,3,4,5,6,7]])
d3 = np.array([[[1,2,3,4,5,6]]])

In [9]:
print(d2.ndim)
print(d3.ndim)

2
3


In [10]:
d2 = np.array([[1,2,3],[1,2,3]])
print(d2)
print(d2.ndim)

[[1 2 3]
 [1 2 3]]
2


In [11]:
d3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(d3)
print(d3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [12]:
dn = np.array([1,2,3,4],ndmin=10)
print(dn)
print(dn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Zeros

In [13]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4),float)
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones 

In [14]:
ar_one = np.ones(4)
ar_ones1 = np.ones((3,4))
print(ar_one)
print(ar_ones1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Empty Array

In [15]:
empty = np.empty(4) 
print(empty)

[1. 1. 1. 1.]


## Range

In [16]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [17]:
## Diagnol

In [18]:
ar_dia = np.eye(3)
ar_dia_2 = np.eye(5,3)
print(ar_dia)
print(ar_dia_2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Linespace

In [19]:
ar_lin = np.linspace(1,20,num= 20,)
print(ar_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


## Random

## Rand()

In [20]:
var = np.random.rand(4)
print(var)

[0.06630389 0.17924561 0.83997406 0.43195355]


In [21]:
var1 = np.random.rand(2,5,)
var1

array([[0.52272998, 0.63586783, 0.3361923 , 0.24259454, 0.03069596],
       [0.87870195, 0.59395773, 0.57181194, 0.01874165, 0.13136388]])

## randn()

In [22]:
var2 = np.random.randn()
print(var2)

0.20144219310736633


## randf()

In [23]:
var3 = np.random.ranf((3,4))
print(var3)

[[0.92188191 0.67751476 0.25414675 0.0737818 ]
 [0.70895831 0.20376962 0.4270659  0.39365646]
 [0.05829419 0.20371909 0.01602552 0.17023109]]


## randint()

In [24]:
var4 = np.random.randint(1,5,(2,3))
print(var4)

[[3 3 4]
 [3 4 2]]


In [25]:
x = np.random.choice([i for i in range(100)],size=(20,2))
x

array([[87, 45],
       [61, 31],
       [15, 28],
       [45, 18],
       [33, 89],
       [30, 25],
       [31, 28],
       [58, 80],
       [76,  1],
       [94,  7],
       [96, 51],
       [19, 98],
       [84, 73],
       [ 1, 94],
       [49, 11],
       [99, 33],
       [60, 16],
       [63, 44],
       [56, 87],
       [65, 63]])

## Random Distribution

In [26]:
a = [0.2,0.3,0.4,.1]
a

[0.2, 0.3, 0.4, 0.1]

In [27]:
x = np.random.choice([i for i in range(4)],p = a,size = (2,90))
x

array([[3, 2, 1, 2, 2, 2, 1, 3, 2, 2, 2, 2, 2, 3, 1, 1, 1, 2, 1, 0, 2, 0,
        2, 1, 2, 2, 3, 2, 0, 2, 2, 1, 2, 0, 2, 2, 0, 2, 2, 3, 2, 2, 0, 2,
        1, 2, 0, 2, 1, 0, 2, 2, 1, 2, 0, 1, 2, 3, 2, 0, 1, 2, 2, 1, 1, 2,
        2, 2, 2, 3, 2, 3, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 3, 1, 0, 2, 2, 1,
        0, 2],
       [0, 3, 1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 0, 2, 0, 3, 0, 1, 1, 0, 1, 2,
        1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1,
        1, 2, 2, 2, 1, 1, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 2, 2, 1, 1, 0, 3,
        2, 2, 1, 1, 0, 0, 0, 1, 0, 2, 2, 2, 0, 2, 2, 1, 2, 0, 0, 0, 2, 2,
        1, 1]])

In [28]:
## Shuffling Arrays

In [29]:
arr = np.array([i for i in range(10)])
np.random.shuffle(arr)
arr

array([5, 7, 1, 0, 9, 8, 3, 6, 4, 2])

## Generating Permutation of Arrays

In [30]:
arr = np.array([i for i in range(5)])
print(np.random.permutation(arr)) #-----> leaves the original array same


[4 3 0 2 1]


# Data Types in Numpy

In [31]:
var = np.array(['F','v'])
type(var.dtype)

numpy.dtype[str_]

In [32]:
x = np.array([1,2,3,4,5],dtype='i')
print(x.dtype)

int32


In [33]:
x1 = np.array([0,1,0,1],dtype='f')
print(x1.dtype)
print(x1)

float32
[0. 1. 0. 1.]


In [34]:
x2 = np.array([0,1,0,1],dtype='i')
new = np.float32(x)
print(x2.dtype)
print(x1)
print(new.dtype)

int32
[0. 1. 0. 1.]
float32


## Arithematic Operators in Array

In [35]:
var = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [36]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.add(var1,var2)
print(varadd)

[0 2 4 6 8]


In [37]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.subtract(var1,var2)
print(varadd)

[0 0 0 0 0]


In [38]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.multiply(var1,var2)
print(varadd)

[ 0  1  4  9 16]


In [39]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.divide(var1,var2)
print(varadd)

[nan  1.  1.  1.  1.]


/var/folders/q8/dv8fwkl52qx_2yh5w017lk340000gn/T/ipykernel_53831/2257501209.py:3: RuntimeWarning: invalid value encountered in true_divide
  varadd = np.divide(var1,var2)


In [40]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.mod(var1,var2)
print(varadd)

[0 0 0 0 0]


/var/folders/q8/dv8fwkl52qx_2yh5w017lk340000gn/T/ipykernel_53831/1245010291.py:3: RuntimeWarning: divide by zero encountered in remainder
  varadd = np.mod(var1,var2)


In [41]:
var1 = np.array([i for i in range(1,5)])
var2 = np.array([i for i in range(1,5)])
varadd = np.reciprocal(var1)
print((varadd))

[1 0 0 0]


## Arithematic Functions

In [42]:
var = np.array([i  for i in range (1,6)])
print(np.min(var))
print(np.max(var))

1
5


In [43]:
var = np.array([i  for i in range (1,6)])
print(np.argmin(var))
print(np.argmax(var))

0
4


In [44]:
var1 = np.array([[i for i in range(1,5)],[j for j in range(5,9)]])
print(np.max(var1,axis=0))
print(np.sqrt(var1))

[5 6 7 8]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [45]:
var2 = np.array([i for i in range(100)])
print(np.sin(var2))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204
 -0.90557836 -0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388
 -0.98803162 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267
 -0.99177885 -0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267
 -0.91652155 -0.83177474  0.01770193  0.85090352  0.90178835  0.12357312
 -0.76825466 -0.95375265 -0.26237485  0.67022918  0.98662759  0.39592515
 -0.55878905 -0.99975517 -0.521551    0.43616476  0.99287265  0.63673801
 -0.30481062 -0.96611777 -0.7391807   0.1673557   0.92002604  0.82682868
 -0.02655115 -0.85551998 -0.89792768 -0.11478481  0.77389068  0.95105465
  0.25382336 -0.67677196 -0.98514626 -0.38778164  0.56610764  0.99952016
  0.51397846 -0.44411267 -0.99388865 -0.62988799  0.

In [46]:
var2 = np.array([i for i in range(100)])
print(np.cos(var2))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462  0.40808206 -0.54772926 -0.99996083 -0.53283302
  0.42417901  0.99120281  0.64691932 -0.29213881 -0.96260587 -0.74805753
  0.15425145  0.91474236  0.83422336 -0.01327675 -0.84857027 -0.90369221
 -0.12796369  0.76541405  0.95507364  0.26664293 -0.66693806 -0.98733928
 -0.39998531  0.5551133   0.99984331  0.52532199 -0.43217794 -0.99233547
 -0.64014434  0.30059254  0.96496603  0.7421542  -0.16299078 -0.91828279
 -0.82930983  0.02212676  0.85322011  0.89986683  0.11918014 -0.77108022
 -0.95241298 -0.25810164  0.67350716  0.98589658  0.39185723 -0.56245385
 -0.99964746 -0.5177698   0.44014302  0.99339038  0.6333192  -0.30902273
 -0.96725059 -0.73619272  0.17171734  0.92175127  0.82433133 -0.03097503
 -0.85780309 -0.89597095 -0.11038724  0.77668598  0.

In [47]:
var3 = np.array([i for i in range(10)])
print(np.cumsum(var3))

[ 0  1  3  6 10 15 21 28 36 45]


In [48]:
## Shape

In [49]:
var = np.array([[i for i in range(1,5)],[i for i in range(6,10)]])
print(var.shape)

(2, 4)


In [50]:
var1 = np.array([i for i in range(10,20)],ndmin=5)
print(var1.shape)
print(var1)

(1, 1, 1, 1, 10)
[[[[[10 11 12 13 14 15 16 17 18 19]]]]]


In [51]:
## Reshape 

In [52]:
var2 = np.array([i for i in range(15,0,-1)])
x = var2.reshape(5,3)
print(var2.ndim)
print(x.ndim)
print(x)

1
2
[[15 14 13]
 [12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [53]:
var3 = np.array([i for i in range(16,0,-1)])
x1 = var3.reshape(4,2,2)
print(var3.ndim)
print(x2.ndim)
print(x1)


one = x1.reshape(-1)
one

1
1
[[[16 15]
  [14 13]]

 [[12 11]
  [10  9]]

 [[ 8  7]
  [ 6  5]]

 [[ 4  3]
  [ 2  1]]]


array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Broadcasting

In [54]:
var1 = np.array([1,2,3,4])
var2 = np.array([[1],[2],[3],[4]])

print(var1.shape)
print(var2.shape)
print(var1)
print(var2)
print(var1+var2)

(4,)
(4, 1)
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


## Indexing and Slicing

In [55]:
var = np.array([i for i in range(9,5,-1)])
print(var[-1])

6


In [56]:
var1 = np.array([[i for i in range(4,7)],[1,2,3]])
print(var1)
print(var1.ndim)
print(var1[0,1])

[[4 5 6]
 [1 2 3]]
2
5


In [57]:
var2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=4)
print(var2)
print(var2.ndim)
print(var2[0,0,1,1])

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4
5


## Slicing

In [58]:
var = np.array([i for i in range(8)])
print(var)
print(var[::-4])

[0 1 2 3 4 5 6 7]
[7 3]


In [59]:
var2 = np.array([[[i for i in range(8)],[i for i in range(8,0,-1)]]])
print(var2)
print(var2[0,0,1:3])
#print(var2[1,::-1])

[[[0 1 2 3 4 5 6 7]
  [8 7 6 5 4 3 2 1]]]
[1 2]


## Iterating Numpy Arrays

In [60]:
var = np.array([i for i in range(8)])
for i in var:
    print(i)

0
1
2
3
4
5
6
7


In [61]:
var = np.array([[1,2,3],[3,2,1]])
for j in var:
    # print(j)
    for i in j:
        print(i)

1
2
3
3
2
1


In [62]:
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x.shape)
print(x)
print(x.ndim)

for i in x:
    for j in i:
        for k in j:
            print(k)


(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
1
2
3
4
5
6
1
2
3
4
5
6


In [63]:
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=4)
print(x.shape)
print(x)
print(x.ndim)

for i in x:
    for j in i:
        for k in j:
            for l in k :
                print(l)


(1, 2, 2, 3)
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4
1
2
3
4
5
6
1
2
3
4
5
6


In [64]:
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x.shape)
print(x)
print(x.ndim)

for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
    print(i)


(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [65]:
## Toget the iteratons
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=10)
print(x.shape)
print(x)
print(x.ndim)

for i,d in np.ndenumerate(x):
    print(i,d)


(1, 1, 1, 1, 1, 1, 1, 2, 2, 3)
[[[[[[[[[[1 2 3]
         [4 5 6]]

        [[1 2 3]
         [4 5 6]]]]]]]]]]
10
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 0, 0, 0, 0, 1) 2
(0, 0, 0, 0, 0, 0, 0, 0, 0, 2) 3
(0, 0, 0, 0, 0, 0, 0, 0, 1, 0) 4
(0, 0, 0, 0, 0, 0, 0, 0, 1, 1) 5
(0, 0, 0, 0, 0, 0, 0, 0, 1, 2) 6
(0, 0, 0, 0, 0, 0, 0, 1, 0, 0) 1
(0, 0, 0, 0, 0, 0, 0, 1, 0, 1) 2
(0, 0, 0, 0, 0, 0, 0, 1, 0, 2) 3
(0, 0, 0, 0, 0, 0, 0, 1, 1, 0) 4
(0, 0, 0, 0, 0, 0, 0, 1, 1, 1) 5
(0, 0, 0, 0, 0, 0, 0, 1, 1, 2) 6


In [66]:
## Copy

In [67]:
var = np.array([i for i in range(5)])

In [68]:
copy = var.copy()
print(var)
print(copy)

[0 1 2 3 4]
[0 1 2 3 4]


In [69]:
x = np.array([i for i in range(10,0,-1)])
view = x.view()
print(x)
print(view)

[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]


In [70]:
## Join Array

In [71]:
x = np.array([i for i in range(10,0,-1)])
y = np.array([i for i in range(0,10)])
ar = np.concatenate((x,y))
ar

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [72]:
x = np.array([[i for i in range(10,0,-1)],[i for i in range(0,10)]])
y = np.array([[i for i in range(0,10)],[i for i in range(10,0,-1)]])
ar = np.concatenate((x,y),axis = 1)
#ar
ar2 = np.dstack((x,y))
ar2

array([[[10,  0],
        [ 9,  1],
        [ 8,  2],
        [ 7,  3],
        [ 6,  4],
        [ 5,  5],
        [ 4,  6],
        [ 3,  7],
        [ 2,  8],
        [ 1,  9]],

       [[ 0, 10],
        [ 1,  9],
        [ 2,  8],
        [ 3,  7],
        [ 4,  6],
        [ 5,  5],
        [ 6,  4],
        [ 7,  3],
        [ 8,  2],
        [ 9,  1]]])

In [73]:
## Split Array

In [74]:
var = np.array([i for i in range(12)],ndmin=2)
ar = np.array_split(var,3,axis=1)
ar

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [75]:
#Functions in Numpy array

In [76]:
## Search

In [79]:
var = np.array([i for i in range(8)])
x = np.where(var%2 == 0)
print(x)

(array([0, 2, 4, 6]),)


In [87]:
var = np.array([1,2,3,4,6,7,8,9])
x = np.searchsorted(var,[5,6,7,8,9,],side='right')
print(x)

[4 5 6 7 8]


In [88]:
## Sort

In [89]:
var = np.array([3,2,4,56,2,1,56,7,8])
print(np.sort(var))

[ 1  2  2  3  4  7  8 56 56]


In [90]:
var = np.array(['a','r','e','c','f','g'])
print(np.sort(var))

['a' 'c' 'e' 'f' 'g' 'r']


In [93]:
var = np.array(['a','q','w'])
v = [True,False,True]
a = var[v]
print(a)

['a' 'w']
