# Day_1

## Array

In [1]:
import numpy as np

In [2]:
x = [1,2,3,4]
y = np.array(x)

In [3]:
print(type(y))

<class 'numpy.ndarray'>


In [4]:
l = []
for i in range(1,5):
    int_1 = int(input('Enter the data'))
    l.append(int_1)
print(np.array(l))

[ 1  2  3 44]


In [5]:
print(y.ndim)

1


In [6]:
d1 = np.array([1,2,3,4,5,6,7])
d2 = np.array([[1,2,3,4,5,6,7]])
d3 = np.array([[[1,2,3,4,5,6]]])

In [7]:
print(d2.ndim)
print(d3.ndim)

2
3


In [8]:
d2 = np.array([[1,2,3],[1,2,3]])
print(d2)
print(d2.ndim)

[[1 2 3]
 [1 2 3]]
2


In [9]:
d3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(d3)
print(d3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [10]:
dn = np.array([1,2,3,4],ndmin=10)
print(dn)
print(dn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Zeros

In [11]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4),float)
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones 

In [12]:
ar_one = np.ones(4)
ar_ones1 = np.ones((3,4))
print(ar_one)
print(ar_ones1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Empty Array

In [13]:
empty = np.empty(4) 
print(empty)

[1. 1. 1. 1.]


## Range

In [14]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [15]:
## Diagnol

In [16]:
ar_dia = np.eye(3)
ar_dia_2 = np.eye(5,3)
print(ar_dia)
print(ar_dia_2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Linespace

In [17]:
ar_lin = np.linspace(1,20,num= 20,)
print(ar_lin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


## Random

## Rand()

In [18]:
var = np.random.rand(4)
print(var)

[0.83352504 0.88043174 0.3751178  0.16327302]


In [19]:
var1 = np.random.rand(2,5,)
var1

array([[0.56686569, 0.66742147, 0.49313951, 0.99516581, 0.6240897 ],
       [0.33784166, 0.78853984, 0.56155474, 0.76880237, 0.90185195]])

## randn()

In [20]:
var2 = np.random.randn()
print(var2)

-0.5099465961059518


## randf()

In [21]:
var3 = np.random.ranf((3,4))
print(var3)

[[0.82853443 0.07036076 0.85172781 0.4778852 ]
 [0.73243342 0.20266271 0.0551844  0.08320468]
 [0.08111207 0.81752341 0.3142936  0.89806894]]


## randint()

In [22]:
var4 = np.random.randint(1,5,(2,3))
print(var4)

[[2 1 1]
 [4 3 3]]


In [23]:
x = np.random.choice([i for i in range(100)],size=(20,2))
x

array([[41, 13],
       [58, 30],
       [ 1, 25],
       [36, 33],
       [83, 16],
       [18, 88],
       [41, 81],
       [ 0,  2],
       [12, 99],
       [57, 70],
       [53, 23],
       [30, 27],
       [80, 10],
       [14, 88],
       [50, 85],
       [48, 92],
       [86, 35],
       [27, 61],
       [23, 42],
       [51, 59]])

## Random Distribution

In [24]:
a = [0.2,0.3,0.4,.1]
a

[0.2, 0.3, 0.4, 0.1]

In [25]:
x = np.random.choice([i for i in range(4)],p = a,size = (2,90))
x

array([[2, 0, 1, 3, 1, 2, 3, 0, 1, 2, 0, 2, 1, 1, 0, 1, 0, 2, 3, 1, 1, 1,
        2, 1, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 3, 1, 1, 2, 0, 2, 3, 1, 2,
        1, 2, 3, 1, 2, 1, 0, 2, 2, 3, 2, 1, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2,
        2, 3, 2, 2, 2, 1, 3, 3, 1, 2, 2, 0, 2, 2, 0, 0, 0, 3, 2, 0, 2, 2,
        1, 0],
       [1, 0, 0, 2, 2, 2, 3, 1, 2, 2, 1, 0, 1, 1, 0, 3, 1, 2, 3, 0, 1, 3,
        1, 2, 0, 0, 3, 2, 2, 1, 1, 3, 2, 1, 2, 3, 2, 1, 1, 2, 2, 3, 2, 0,
        0, 0, 1, 2, 1, 1, 2, 2, 2, 1, 3, 1, 1, 1, 2, 2, 2, 0, 2, 1, 2, 2,
        2, 2, 2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 1, 1, 0, 0, 1, 1, 3,
        1, 1]])

In [26]:
## Shuffling Arrays

In [27]:
arr = np.array([i for i in range(10)])
np.random.shuffle(arr)
arr

array([5, 3, 4, 6, 0, 1, 2, 8, 9, 7])

## Generating Permutation of Arrays

In [28]:
arr = np.array([i for i in range(5)])
print(np.random.permutation(arr)) #-----> leaves the original array same


[4 1 2 3 0]


# Data Types in Numpy

In [29]:
var = np.array(['F','v'])
type(var.dtype)

numpy.dtype[str_]

In [30]:
x = np.array([1,2,3,4,5],dtype='i')
print(x.dtype)

int32


In [31]:
x1 = np.array([0,1,0,1],dtype='f')
print(x1.dtype)
print(x1)

float32
[0. 1. 0. 1.]


In [32]:
x2 = np.array([0,1,0,1],dtype='i')
new = np.float32(x)
print(x2.dtype)
print(x1)
print(new.dtype)

int32
[0. 1. 0. 1.]
float32


## Arithematic Operators in Array

In [33]:
var = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [34]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.add(var1,var2)
print(varadd)

[0 2 4 6 8]


In [35]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.subtract(var1,var2)
print(varadd)

[0 0 0 0 0]


In [36]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.multiply(var1,var2)
print(varadd)

[ 0  1  4  9 16]


In [37]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.divide(var1,var2)
print(varadd)

[nan  1.  1.  1.  1.]


/var/folders/q8/dv8fwkl52qx_2yh5w017lk340000gn/T/ipykernel_54726/2257501209.py:3: RuntimeWarning: invalid value encountered in true_divide
  varadd = np.divide(var1,var2)


In [38]:
var1 = np.array([i for i in range(5)])
var2 = np.array([i for i in range(5)])
varadd = np.mod(var1,var2)
print(varadd)

[0 0 0 0 0]


/var/folders/q8/dv8fwkl52qx_2yh5w017lk340000gn/T/ipykernel_54726/1245010291.py:3: RuntimeWarning: divide by zero encountered in remainder
  varadd = np.mod(var1,var2)


In [39]:
var1 = np.array([i for i in range(1,5)])
var2 = np.array([i for i in range(1,5)])
varadd = np.reciprocal(var1)
print((varadd))

[1 0 0 0]


## Arithematic Functions

In [40]:
var = np.array([i  for i in range (1,6)])
print(np.min(var))
print(np.max(var))

1
5


In [41]:
var = np.array([i  for i in range (1,6)])
print(np.argmin(var))
print(np.argmax(var))

0
4


In [42]:
var1 = np.array([[i for i in range(1,5)],[j for j in range(5,9)]])
print(np.max(var1,axis=0))
print(np.sqrt(var1))

[5 6 7 8]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [43]:
var2 = np.array([i for i in range(100)])
print(np.sin(var2))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204
 -0.90557836 -0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388
 -0.98803162 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267
 -0.99177885 -0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267
 -0.91652155 -0.83177474  0.01770193  0.85090352  0.90178835  0.12357312
 -0.76825466 -0.95375265 -0.26237485  0.67022918  0.98662759  0.39592515
 -0.55878905 -0.99975517 -0.521551    0.43616476  0.99287265  0.63673801
 -0.30481062 -0.96611777 -0.7391807   0.1673557   0.92002604  0.82682868
 -0.02655115 -0.85551998 -0.89792768 -0.11478481  0.77389068  0.95105465
  0.25382336 -0.67677196 -0.98514626 -0.38778164  0.56610764  0.99952016
  0.51397846 -0.44411267 -0.99388865 -0.62988799  0.

In [44]:
var2 = np.array([i for i in range(100)])
print(np.cos(var2))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462  0.40808206 -0.54772926 -0.99996083 -0.53283302
  0.42417901  0.99120281  0.64691932 -0.29213881 -0.96260587 -0.74805753
  0.15425145  0.91474236  0.83422336 -0.01327675 -0.84857027 -0.90369221
 -0.12796369  0.76541405  0.95507364  0.26664293 -0.66693806 -0.98733928
 -0.39998531  0.5551133   0.99984331  0.52532199 -0.43217794 -0.99233547
 -0.64014434  0.30059254  0.96496603  0.7421542  -0.16299078 -0.91828279
 -0.82930983  0.02212676  0.85322011  0.89986683  0.11918014 -0.77108022
 -0.95241298 -0.25810164  0.67350716  0.98589658  0.39185723 -0.56245385
 -0.99964746 -0.5177698   0.44014302  0.99339038  0.6333192  -0.30902273
 -0.96725059 -0.73619272  0.17171734  0.92175127  0.82433133 -0.03097503
 -0.85780309 -0.89597095 -0.11038724  0.77668598  0.

In [45]:
var3 = np.array([i for i in range(10)])
print(np.cumsum(var3))

[ 0  1  3  6 10 15 21 28 36 45]


In [46]:
## Shape

In [47]:
var = np.array([[i for i in range(1,5)],[i for i in range(6,10)]])
print(var.shape)

(2, 4)


In [48]:
var1 = np.array([i for i in range(10,20)],ndmin=5)
print(var1.shape)
print(var1)

(1, 1, 1, 1, 10)
[[[[[10 11 12 13 14 15 16 17 18 19]]]]]


In [49]:
## Reshape 

In [50]:
var2 = np.array([i for i in range(15,0,-1)])
x = var2.reshape(5,3)
print(var2.ndim)
print(x.ndim)
print(x)

1
2
[[15 14 13]
 [12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [51]:
var3 = np.array([i for i in range(16,0,-1)])
x1 = var3.reshape(4,2,2)
print(var3.ndim)
print(x2.ndim)
print(x1)


one = x1.reshape(-1)
one

1
1
[[[16 15]
  [14 13]]

 [[12 11]
  [10  9]]

 [[ 8  7]
  [ 6  5]]

 [[ 4  3]
  [ 2  1]]]


array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Broadcasting

In [61]:
var1 = np.array([1,2,3,4])
var2 = np.array([[1],[2],[3],[4]])

print(var1.shape)
print(var2.shape)
print(var1)
print(var2)
print(var1+var2)

(4,)
(4, 1)
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


## Indexing and Slicing

In [64]:
var = np.array([i for i in range(9,5,-1)])
print(var[-1])

6


In [67]:
var1 = np.array([[i for i in range(4,7)],[1,2,3]])
print(var1)
print(var1.ndim)
print(var1[0,1])

[[4 5 6]
 [1 2 3]]
2
5


In [110]:
var2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=4)
print(var2)
print(var2.ndim)
print(var2[0,0,1,1])

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4
5


## Slicing

In [98]:
var = np.array([i for i in range(8)])
print(var)
print(var[::-4])

[0 1 2 3 4 5 6 7]
[7 3]


In [107]:
var2 = np.array([[[i for i in range(8)],[i for i in range(8,0,-1)]]])
print(var2)
print(var2[0,0,1:3])
#print(var2[1,::-1])

[[[0 1 2 3 4 5 6 7]
  [8 7 6 5 4 3 2 1]]]
[1 2]


## Iterating Numpy Arrays

In [112]:
var = np.array([i for i in range(8)])
for i in var:
    print(i)

0
1
2
3
4
5
6
7


In [116]:
var = np.array([[1,2,3],[3,2,1]])
for j in var:
    # print(j)
    for i in j:
        print(i)

1
2
3
3
2
1


In [120]:
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x.shape)
print(x)
print(x.ndim)

for i in x:
    for j in i:
        for k in j:
            print(k)


(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
1
2
3
4
5
6
1
2
3
4
5
6


In [121]:
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=4)
print(x.shape)
print(x)
print(x.ndim)

for i in x:
    for j in i:
        for k in j:
            for l in k :
                print(l)


(1, 2, 2, 3)
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4
1
2
3
4
5
6
1
2
3
4
5
6


In [134]:
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x.shape)
print(x)
print(x.ndim)

for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
    print(i)


(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [138]:
## Toget the iteratons
x = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],ndmin=10)
print(x.shape)
print(x)
print(x.ndim)

for i,d in np.ndenumerate(x):
    print(i,d)


(1, 1, 1, 1, 1, 1, 1, 2, 2, 3)
[[[[[[[[[[1 2 3]
         [4 5 6]]

        [[1 2 3]
         [4 5 6]]]]]]]]]]
10
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 0, 0, 0, 0, 1) 2
(0, 0, 0, 0, 0, 0, 0, 0, 0, 2) 3
(0, 0, 0, 0, 0, 0, 0, 0, 1, 0) 4
(0, 0, 0, 0, 0, 0, 0, 0, 1, 1) 5
(0, 0, 0, 0, 0, 0, 0, 0, 1, 2) 6
(0, 0, 0, 0, 0, 0, 0, 1, 0, 0) 1
(0, 0, 0, 0, 0, 0, 0, 1, 0, 1) 2
(0, 0, 0, 0, 0, 0, 0, 1, 0, 2) 3
(0, 0, 0, 0, 0, 0, 0, 1, 1, 0) 4
(0, 0, 0, 0, 0, 0, 0, 1, 1, 1) 5
(0, 0, 0, 0, 0, 0, 0, 1, 1, 2) 6
